messages:
  alreadyRunning: "&c&lGame | &7The game is already running!"
  noPermission: "&c&lGame | &7You do not have permission to do that!"
  gameStarted: "&c&lGame | &7Squidgame has started! /game join squidgame to join!"
  alreadyStarted: "&c&lGame | &7The game has already started!"
  locationSet: "&c&lGame | &7The teleport location has been set!"
  joinSuccess: "&c&LGame | &7You have successfully joined the game!"
  redLight: "&c&lGame | &7Stop! &cRed light!"
  greenLight: "&c&lGame | &7Go! &aGreen light!"
  positionOneSet: "&c&lGame | &7Position one has been set!"
  positionTwoSet: "&c&lGame | &7Position two has been set!"
teleportLocation:
  location:
  pos1:
  pos2:
deathCommands:
  - "say hi"
